In [1]:
import numpy as np


In [2]:
from field_np import Field_np
from point_np import Point_np

In [3]:
field_str = "000801005900000010700000002070000000003000100010040200007400000000000068008706000"
fld = Field_np()



FieldMap():
	row_all: range(0, 9)
	row_excl: range(9, 17)
	column_all: range(17, 26)
	column_excl: range(26, 34)
	square_all: range(34, 43)
	square_excl: range(43, 51)
	related_all: range(51, 72)
	related_excl: range(72, 92)
	squares_v_all: range(92, 119)
	squares_v_excl: range(119, 145)
	squares_h_all: range(145, 172)
	squares_h_excl: range(172, 198)


In [4]:
fld.enter_values(field_str)

In [5]:
pt50 = Point_np(50, fld)
pt50

In [6]:
pt50

In [7]:
pt50.possible_values

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [8]:
pt50.possible_values

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [9]:
mapping = fld.fld_map._point_mappings_np

In [10]:
fld.fld_map.row_column_by_pos(pt50.position)

(5, 5)

In [12]:
# aa = pt50.get_all_related_points()[:,:][0, pt50.get_all_related_points()[0, :] > 0]
# 2 in np.unique(aa.tolist())

In [17]:
pt50.get_all_related_points()

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [13]:
pt50.restrict_by_neighbours()

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [ ]:
fld.fld

In [ ]:
impossible_vals = pt50.get_all_related_points()[:, :][0, pt50.get_all_related_points()[0, :] > 0]
np.unique(impossible_vals)

In [ ]:
np.flatnonzero(pt50.possible_values)+1

In [ ]:
pv = pt50.possible_values
pv


In [ ]:
pt50.impossible_values

In [ ]:
np.flatnonzero(pt50.parent.fld[1:, pt50.position] == 0)+1

In [ ]:
len(pt50.possible_values)

In [ ]:
asas = np.array([Point_np(i, fld) for i in range(81)])
asas

In [24]:
np.flatnonzero(fld.fld[0,:]==0)


array([ 0,  1,  2,  4,  6,  7, 10, 11, 12, 13, 14, 15, 17, 19, 20, 21, 22,
       23, 24, 25, 27, 29, 30, 31, 32, 33, 34, 35, 36, 37, 39, 40, 41, 43,
       44, 45, 47, 48, 50, 52, 53, 54, 55, 58, 59, 60, 61, 62, 63, 64, 65,
       66, 67, 68, 69, 72, 73, 76, 78, 79, 80], dtype=int64)

In [23]:
np.reshape(fld.fld[0,:], (9,9))



array([[0, 0, 0, 8, 0, 1, 0, 0, 5],
       [9, 0, 0, 0, 0, 0, 0, 1, 0],
       [7, 0, 0, 0, 0, 0, 0, 0, 2],
       [0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 4, 0, 2, 0, 0],
       [0, 0, 7, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 6, 8],
       [0, 0, 8, 7, 0, 6, 0, 0, 0]], dtype=int8)

In [29]:
from from_str_field import parse_field

In [35]:
from field import Field
f = Field()
f.enter_values([[0, 0, 0, 0, 9, 7, 0, 0, 6],
                [5, 0, 0, 2, 0, 0, 1, 0, 4],
                [3, 0, 0, 0, 0, 1, 0, 7, 0],
                [0, 9, 3, 8, 0, 5, 0, 0, 7],
                [0, 0, 0, 0, 1, 0, 0, 0, 0],
                [4, 0, 0, 7, 0, 6, 5, 9, 0],
                [0, 4, 0, 1, 0, 0, 0, 0, 9],
                [8, 0, 2, 0, 0, 9, 0, 0, 1],
                [9, 0, 0, 6, 4, 0, 0, 0, 0]], False)
f.get_values_as_str()

'000097006500200104300001070093805007000010000400706590040100009802009001900640000'

[]